
import Dados.Cliente;
import Dao.SistemaDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alves
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }

        public Clientes(String Cnpj, String nome, String cidade, String cep,String email,String telefone, String operacao) {
    
        initComponents();
        txtCnpj.setText(Cnpj);
        txtNome.setText(nome);
        txtCidade.setText(cidade);
        txtCep.setText(cep);
        txtEmail.setText(email);
        txtTelefone.setText(telefone);
       
        if (operacao.equals("excluir")) {
            btnExcluir.setVisible(true);
            btnSalvar.setVisible(false);
            btnAlterar.setVisible(false);
            txtCnpj.setEnabled(false);
            txtNome.setEnabled(false);
            txtCidade.setEnabled(false);
            txtCep.setEnabled(false);
            txtEmail.setEnabled(false);
            txtTelefone.setEnabled(false);
           
        } else if (operacao.equals("alterar")) {
            btnAlterar.setVisible(true);
            btnSalvar.setVisible(false);
            btnExcluir.setVisible(false);
            txtCnpj.setEnabled(false);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Clientes");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 50, 37, 18);

        jLabel2.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        jLabel2.setText("Cidade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 42, 18);

        jLabel3.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        jLabel3.setText("CEP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 150, 30, 18);

        jLabel5.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        jLabel5.setText("Telefone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 100, 60, 18);

        jLabel4.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 50, 18);

        jLabel7.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        jLabel7.setText("CNPJ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 50, 32, 18);
        getContentPane().add(txtCnpj);
        txtCnpj.setBounds(92, 47, 176, 22);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(92, 103, 176, 22);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(92, 156, 176, 22);
        getContentPane().add(txtNome);
        txtNome.setBounds(390, 50, 162, 22);
        getContentPane().add(txtCep);
        txtCep.setBounds(390, 150, 162, 22);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(390, 100, 160, 22);

        btnAlterar.setBackground(new java.awt.Color(102, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(350, 240, 100, 40);

        btnSalvar.setBackground(new java.awt.Color(102, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        btnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarKeyPressed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(30, 240, 100, 40);

        btnExcluir.setBackground(new java.awt.Color(102, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(190, 240, 100, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\alves\\Downloads\\imagens para o trabalho em java\\soft-ice-cream_1f366.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 560, 300);

        setSize(new java.awt.Dimension(576, 326));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        Cliente cliente = new Cliente();
        
        
        cliente.setCnpj(txtCnpj.getText());
        cliente.setNome(txtNome.getText());
        cliente.setCidade(txtCidade.getText());
        cliente.setCep(txtCep.getText());
        cliente.setEmail(txtEmail.getText());
        cliente.setTelefone(txtTelefone.getText());
        try {

            SistemaDao dao;
            dao = new SistemaDao();
            dao.alterarClientes(cliente);

            JOptionPane.showMessageDialog(null, "Usuário alterado com sucesso");

            dispose();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Mensagem de erro:" + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Cliente cliente = new Cliente();
       
        
        cliente.setCnpj(txtCnpj.getText());
        cliente.setNome(txtNome.getText());
        cliente.setCidade(txtCidade.getText());
        cliente.setCep(txtCep.getText());
        cliente.setEmail(txtEmail.getText());
        cliente.setTelefone(txtTelefone.getText());


        SistemaDao dao;
        dao = new SistemaDao();
        try {
            dao.salvarClientes(cliente);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
        txtCnpj.setText("");
        txtNome.setText("");
        txtCidade.setText("");
        txtCep.setText("");
        txtEmail.setText("");
        txtTelefone.setText("");
        txtCnpj.requestFocus();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnSalvar.doClick();
        }
    }//GEN-LAST:event_btnSalvarKeyPressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         Cliente cliente = new Cliente();
        int resposta;
        resposta = JOptionPane.showConfirmDialog(null, "Confirma?", "Confirmação", 0);

        if (resposta == 0) {
            cliente.setCnpj(txtCnpj.getText());

            try {

                SistemaDao dao;
                dao = new SistemaDao();
                dao.excluirClientes(cliente);

                JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso");

                dispose();

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Mensagem de erro:" + ex.getMessage());
            }

        } else {
            dispose();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
